Fix broken Markdown headings with quotes
Redocly/redoc pull request #1513
Opened 2021-02-02 09:44 UTC by Grandbrain

2022-03-23 15:17 UTC, RomanHotsiy commented
Related https://github.com/Redocly/redoc/pull/1553

2022-04-15 08:26 UTC, zalesky requested changes

2022-04-15 08:26 UTC, zalesky commented on src/services/MenuStore.ts
> +  }
```suggestion
  private static escapeQuotes(str: string) : string {
    return str.replace(/["\\]/g, '\\$&');
  }
```
Also `src/utils/helpers.ts` much better place for this function, near existing `unescapeHTMLChars`

2022-04-15 13:04 UTC, Oprysk approved these changes

2022-04-15 13:25 UTC, zalesky approved these changes

2022-04-15 13:35 UTC, anastasiia-developer commented
@Grandbrain Hi!  Thank you for your contribution to redoc.

2022-04-15 13:53 UTC, merged