MenuBuilder: Add support for `sortOperationsAlphabetically`
Redocly/redoc pull request #1843
Opened 2021-12-27 07:18 UTC by flouthoc

Already documented but is currently `NO-OP` and not implemented
`sortOperationsAlphabetically`.

Allows sorting operations in sidebar menu according to their `name`
configured which is by default `summary` from Swaggerspec

TLDR:
Following commit adds support for `sortOperationsAlphabetically` already
documented but not implemented here: https://redoc.ly/docs/api-reference-docs/guides/migration-guide-2-0/#automated-sorting

2021-12-27 10:53 UTC, flouthoc commented
@RomanHotsiy PTAL

2021-12-27 10:57 UTC, RomanHotsiy requested changes
Left a small comment.

2021-12-27 10:57 UTC, RomanHotsiy commented on src/services/MenuBuilder.ts
> +    }
```suggestion
      res.sort((a, b) => a.name.localeCompare(b.name));
    }
```

2021-12-27 11:07 UTC, flouthoc commented on src/services/MenuBuilder.ts
> +    }
resolved in latest commit.

2021-12-27 11:18 UTC, flouthoc commented
@RomanHotsiy Thanks fixed :)

2021-12-29 09:41 UTC, flouthoc commented
@RomanHotsiy Let me know if anything else needs to be done. :)

2021-12-29 11:33 UTC, Oprysk approved these changes

2021-12-29 15:37 UTC, RomanHotsiy approved these changes

2021-12-29 17:42 UTC, rhatdan commented
Can this be merged now?

2021-12-30 12:31 UTC, merged