fix: merge allOf in correct order
Redocly/redoc pull request #2020
Opened 2022-05-23 11:25 UTC by AlexVarchuk

## What/Why/How?

## Reference

## Testing

## Screenshots (optional)

## Check yourself

- [ ] Code is linted
- [ ] Tested
- [ ] All new/updated code is covered with tests

2022-05-23 12:53 UTC, Oprysk approved these changes

2022-05-23 13:39 UTC, RomanHotsiy requested changes

2022-05-23 13:39 UTC, RomanHotsiy commented on src/services/OpenAPIParser.ts
> +        receiver.oneOf = [...(receiver?.oneOf || []), ...oneOf];
This is not 100% valid. We can't just merge oneOf's. But this is not needed. We hoist oneOfs to the top-level before.

2022-05-23 13:39 UTC, RomanHotsiy commented on src/services/OpenAPIParser.ts
> +        receiver.anyOf = [...(receiver?.oneOf || []), ...anyOf];
Same here.

2022-05-23 13:39 UTC, RomanHotsiy commented on src/services/OpenAPIParser.ts
> +        receiver.examples = [...(receiver.examples || []), ...examples];
I think we shouldn't merge examples too. Let's just overwrite.

2022-05-25 11:31 UTC, anastasiia-developer approved these changes

2022-05-26 11:18 UTC, RomanHotsiy approved these changes

2022-05-26 11:54 UTC, merged