feat: add clear cache for publish action
Redocly/redoc pull request #2129
Opened 2022-08-10 15:55 UTC by AlexVarchuk

## What/Why/How?
invalidate cache on jsDelivr and Redocly CDN
## Reference

## Testing

## Screenshots (optional)

## Check yourself

- [x] Code is linted
- [ ] Tested
- [ ] All new/updated code is covered with tests

2022-08-10 22:30 UTC, RomanHotsiy requested changes
Left some change requests

2022-08-10 22:30 UTC, RomanHotsiy commented on .github/workflows/publish.yml
> +  clearing-cache:
let's rename to `invalidate-cache`

2022-08-10 22:30 UTC, RomanHotsiy commented on .github/workflows/publish.yml
> +          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
Let's put everything into single `invalidate-cache.sh` script and remove `npm run clear-cache`

2022-08-17 09:55 UTC, Oprysk approved these changes

2022-08-18 13:50 UTC, RomanHotsiy approved these changes

2022-08-18 13:56 UTC, merged