guard against nullable allOf
Redocly/redoc pull request #2176
Opened 2022-09-27 13:14 UTC by brunomartinspro

## What/Why/How?
Running Redoc on Safari macOS or older version of Chrome triggers a an error: "Cannot read properties of null(reading'allOf')"

## Testing
This can be reproduced when opening redoc for the first time with older versions of chrome (for example https://filehippo.com/download_google-chrome/87.0.4280.66/post_download/)
However, after a refresh the error disappears. It only happens once when a user opens redoc for the first time.

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/7645736/192535501-862207d5-c721-4f2c-b06e-3562c1ac46ff.png)

2022-09-28 08:40 UTC, AlexVarchuk requested changes
I think we should find the place in the code where we pass `null` value of the schema to `mergeAllOf` function, understand why it happens, and fix it there.
Maybe this problem is more deeply than we think.

I tried to run it on Safari and Chrome v87 on macOs, and it works correctly. Maybe it related to special case on the definition.
Please add more details to reproduce this case (definition, version of Safari etc.).

2022-09-28 08:48 UTC, brunomartinspro commented
@AlexVarchuk i will try to add more context.
The error only happens the first time you open it. specifically with our VuePress documentation on https://developer.signicat.com/dtp/apis/mobileid/

2022-09-28 11:09 UTC, AlexVarchuk commented
> @AlexVarchuk i will try to add more context. The error only happens the first time you open it. specifically with our VuePress documentation on https://developer.signicat.com/dtp/apis/mobileid/ Just reproduced it in the latest version of edge.. i will keep looking into it ![image](https://user-images.githubusercontent.com/7645736/192736501-0a743e98-9700-4a42-ba27-74f27ebeb76b.png) Stacktrace

I checked it. It sometimes reproduces in the last version of Chrome. I am not sure why schema is null in some cases.
Maybe it is related to `specUrl`, but I don't have a strong opinion about that for now.

2022-09-28 15:40 UTC, AlexVarchuk commented
@brunomartinspro Hi seems I found out why it happened. For some reason your URL sends an invalid definition.
This includes `oneOf` with `null` value which is unexpected.


<img width="657" alt="Screenshot 2022-09-28 at 18 25 35" src="https://user-images.githubusercontent.com/14113673/192820184-e18a209f-ac70-4f4c-b594-342e8b7e2ce6.png">

https://user-images.githubusercontent.com/14113673/192823388-90a44eed-7429-4557-b1d1-1c2bf67c6b0f.mov

It is very hard to catch.
I think you use some tools for autogenerate definition.

2022-09-29 09:10 UTC, brunomartinspro commented
Thank you @AlexVarchuk for debugging this and finding the issue.
Since this is a generator error i will close this pull request.

Thank you for your time.

2022-09-29 09:10 UTC, closed without merging